export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';


// MESSAGE
export const MESSAGE_ADD_TO_CART = 'MESSAGE_ADD_TO_CART';
export const MESSAGE_REMOVE_FROM_CART = 'MESSAGE_REMOVE_FROM_CART';
export const MESSAGE_CLOSE_NOTIFICATION = 'MESSAGE_CLOSE_NOTIFICATION';